config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, except: %i(index)

  resources :disks do
    patch 'upload_files', on: :member
    delete 'delete_files', on: :member
  end

  devise_scope :user do
    root to: "users#show"
  end

  unauthenticated do
    root to: 'home#show', as: 'unauthenticated'
  end

  authenticated :user do
    root to: 'sessions#new', as: 'authenticated'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/disk.rb
class Disk < ApplicationRecord

  belongs_to :user
  has_many_attached :files

  # set maximum available disk space in megabytes (10Mb)
  DISK_LIMIT = 10.megabytes.freeze

  # set maximum maximum file size in megabytes (4Mb)
  MAX_FILE_SIZE = 4.megabytes.freeze

  # set available extentions
  PERMITTED_EXTENTIONS = ['application/zip',
                          'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                          'application/vnd.openxmlformats-officedocument.wordprocessingml.document'].freeze

  before_validation :free_disk_space

  validates :files,
            size: { less_than: MAX_FILE_SIZE,
                    message: "size more than #{ActionController::Base.helpers.number_to_human_size(MAX_FILE_SIZE)}" },
            content_type: { in: PERMITTED_EXTENTIONS,
                            message: "support only docx, xlsx, zip" }

  validate :enough_disk_space

  private

  def free_disk_space
    DISK_LIMIT - files_blobs.sum(:byte_size)
  end

  def enough_disk_space
    if files.attached?
      if files.blobs.last.byte_size > free_disk_space
        ActiveStorage::Attachment.find(files.blobs.last.id).purge
        errors.add(:files, "Disk limit exceeded #{ActionController::Base.helpers.number_to_human_size(DISK_LIMIT)}")
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord

  has_one :disk

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, uniqueness: true, length: { maximum: 255 }

  validates :user_name,
            uniqueness: true,
            length: { maximum: 15 },
            presence: true


  validates_format_of :user_name, with: /\A[a-zA-Z0-9_]{2,15}\Z/,
                      message: "User name must be Alphanumeric",
                      multiline: true

  validates_format_of :password,
                      with: /^(?=.*[A-z])(?=.*[0-9])(?=.*[!@#$%!?`~^&*()\-__+.]).{8,30}$/,
                      multiline: true,
                      message: 'Password should have more than 8 and smolder 30 characters,
                                including uppercase letters,
                                numbers and special character'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:user_name,
               :email,
               :password,
               :password_confirmation,
               :remember_me)
    end
  end
end

app/controllers/disks_controller.rb
class DisksController < ApplicationController
  before_action :set_current_user, :set_disk

  def upload_files
    if params[:disk][:files].present?

      params[:disk][:files].each do |file|
        if @disk.files.attach(file)
          redirect_to @user, notice: 'file was successfully uploaded.'
        else
          redirect_to @user, notice: @disk.errors.messages
        end
      end
    end
  end

  def delete_files
    ActiveStorage::Attachment.find(params[:id]).purge
    redirect_to @user, notice: 'file was successfully deleted.'
  end

  private

  def set_current_user
    @user = current_user
  end

  def set_disk
    @disk = Disk.find_or_create_by(user_id: @user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_current_user, except: [:show, :create]
  before_action :authenticate_user!

  def show
    @user = User.find(current_user.id)
    @disk = Disk.find_by(params[@user.id])
  end

  def create
    @user = User.new(user_params)
  
    if @user.save
      @disk = Disk.create(user_id: @user.id)
      redirect_to @user, notice: 'User was successfully created.'
    else
      render 'devise/registration/new'
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'user was successfully updated.'
    else
      render :show
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path, notice: 'User was successfully destroyed.'
  end

  private

  def set_current_user
    # @user = User.find(params[:id])
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:user_name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def image_by_file_type(file_type)
    images =
      {
        Disk::PERMITTED_EXTENTIONS[0] => "zip.svg",
        Disk::PERMITTED_EXTENTIONS[1] => "xls.svg",
        Disk::PERMITTED_EXTENTIONS[2] => "doc.svg"
      }

    image_tag asset_pack_path("media/images/#{images[file_type]}")
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def show_disk_space
    if @user.disk.present?
      Disk::DISK_LIMIT - @user.disk.files.map(&:byte_size).sum
    else
      Disk::DISK_LIMIT
    end
  end

  def file_name_without_ext(file)
    filename = file.filename.to_s
    File.basename(filename, File.extname(filename))
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>XDisk</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag asset_pack_path('media/images/favicon.svg') %>
    <%= stylesheet_pack_tag 'app', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/partials/_form_errors.html.erb
<% errors = model.errors %>

<% if errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <div class="lead buffer-bottom">
      <%= t :error, count: errors.count %>
    </div>

    <ul>
      <% errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_upload.html.erb
<div>
  <%= form_for @disk, url: upload_files_disk_path(@disk) do |f| %>

    <div class="field">
      <ul>
        <%= f.label :files %><br/>
        <%= f.file_field :files,
                         placeholder: 'Upload files',
                         multiple: true,
                         accept: "#{Disk::PERMITTED_EXTENTIONS.join(', ')}"
        %>
        <div class='actions'>
          <%= f.submit '+ upload',
                       method: :patch,
                       title: 'upload files',
                       class: 'btn btn-block btn-success fa fa-plus'
          %><br/>
        </div>
      </ul>
  <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= render partial: 'partials/form_errors',
           locals: { model: @user } %>

<% if user_signed_in? %>
  <div class="row">
    <div class="col-sm-3">
      <div class="panel panel-dark-outline tabs-panel">
        <div class="panel-heading"><h4 class="no-margin-top"> <%= @user.user_name %></h4>
          <div class="nav nav-tabs pull-left type-document">
            <%= link_to 'Edit', edit_user_registration_path(@user) %>
            <%= button_to 'sign_out', destroy_user_session_path, method: :delete %>

          </div>
          <div class="clear"></div>
        </div>
        <div class="panel-body tab-content">
          <div class="tab-pane active documents-panel">
            <div class="clear">
              <div class="v-spacing-xs">

              </div>
            </div>
            <ul class="folders list-unstyled">
              <li>
                <i class="fa fa-folder"></i> Files quantity: <%= @user.disk.files.all.count if @user.disk.present? %>
              </li>
              <li><i class="fa fa-folder"></i> Disk free space:
                <%= number_to_human_size(show_disk_space,
                                         precision: 3,
                                         separator: ',') %>
              </li>
            </ul>
            <div class="v-spacing-xs">
              <%= render 'upload', user: @user %></div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-8 tab-content no-bg no-border">
      <% if @user.disk.present? %>
        <div class="row">
          <div class="col-12">
            <div class="card-box">
              <div class="row">
                <div class="col-lg-6 col-xl-6">
                  <h4 class="header-title m-b-30">My Files</h4>
                </div>
              </div>
              <div class="row">
                <% @user.disk.files.blobs.each do |file| %>
                  <div class="col-lg-3 col-xl-2">
                    <a class="file-close">
                      <%= button_to delete_files_disk_path(file),
                                    method: :delete,
                                    data: { confirm: "delete file #{file.filename} from disk?" },
                                    class: 'button btn btn-icon btn-danger file-close' do %>
                        </a>
                        <i class='fa fa-trash'></i>
                      <% end %>
                      <div class="file-img-box">
                        <%= image_by_file_type(file.content_type) %>
                      </div>
                      <a class="file-download">
                        <%= link_to rails_blob_path(file, disposition: "attachment") do %>
                          <i class="fa fa-download"></i>
                          </a>
                        <% end %>
                        <div class="file-man-title">
                          <h5 class="mb-0 text-overflow"><%= file_name_without_ext(file) %></h5>
                          <p class="mb-0">
                            <small>
                              <%= number_to_human_size(file.byte_size) %>
                              <%= file.created_at.strftime("%d %b. %Y") %>
                            </small>
                          </p>
                        </div>
                        </div>
                <% end %>
              </div>
      <% end %>
      </div>
      </div>
      </div>
    </div>
  </div>

<% else %>
  <%= render 'form', user: @user %>
<% end %>